version: 2.1

jobs:
  print_hello:
    docker: # it uses the docker executor
      - image: circleci/node:13.8.0
    steps:
      - run: echo "hello"

  print_world:
    docker: # it uses the docker executor
      - image: circleci/node:13.8.0
    steps:
      - run: echo "world"

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello
