version: 2.1

defaults: &defaults
  docker: # it uses the docker executor
    - image: circleci/node:13.8.0

commands:
  print_pipeline_id:
    description: "Print pipeline ID"
    steps:
      - run: echo "${CIRCLE_WORKFLOW_ID}"
jobs:
  save_hello_world_output:
    <<: *defaults
    steps:
      - print_pipeline_id
      - run: echo "hello world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  error_job:
    <<: *defaults
    steps:
      - run: |
          return 1
      - run:
          name: Log error
          command: echo "Hello Error"
          shell: /bin/bash
          when: on_fail
  print_output_file:
    <<: *defaults
    steps:
      - print_pipeline_id
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt

# Orchestrate or schedule a set of jobs
workflows:
  sample_workflow:
    # Run the welcome/run job in its own container
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      - error_job
