version: 2.1

jobs:
  print_hello:
    docker: # it uses the docker executor
      - image: circleci/node:13.8.0
    steps:
      - run: echo "hello"

  print_world:
    docker: # it uses the docker executor
      - image: circleci/node:13.8.0
    steps:
      - run: echo "world"
  save_hello_world_output:
    docker: # it uses the docker executor
      - image: circleci/node:13.8.0
    steps:
      - run: echo "hello world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  print_output_file:
    docker: # it uses the docker executor
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "echo an env var that is part of the project on circleci"
          command: |
            echo $MY_NAME # this env var is defined within the project

# Orchestrate or schedule a set of jobs
workflows:
  sample_workflow:
    # Run the welcome/run job in its own container
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
